// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIL70AJtlxSAu5CWLfJcX0hjMtjuhDlMs',
    appId: '1:700953421587:web:e0ceed38ede56409db9ce6',
    messagingSenderId: '700953421587',
    projectId: 'students-7ae0a',
    authDomain: 'students-7ae0a.firebaseapp.com',
    storageBucket: 'students-7ae0a.appspot.com',
    measurementId: 'G-CH2X5CKX2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjN6qzNHMIwn_Xj7pCCyfWvQexuuXWfA',
    appId: '1:700953421587:android:69063fcd42065506db9ce6',
    messagingSenderId: '700953421587',
    projectId: 'students-7ae0a',
    storageBucket: 'students-7ae0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsL0nG7Aui0GIzMPBOjrxDPHQkAJPGf6A',
    appId: '1:700953421587:ios:638d053767d674c4db9ce6',
    messagingSenderId: '700953421587',
    projectId: 'students-7ae0a',
    storageBucket: 'students-7ae0a.appspot.com',
    iosBundleId: 'com.example.studentsFollowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsL0nG7Aui0GIzMPBOjrxDPHQkAJPGf6A',
    appId: '1:700953421587:ios:638d053767d674c4db9ce6',
    messagingSenderId: '700953421587',
    projectId: 'students-7ae0a',
    storageBucket: 'students-7ae0a.appspot.com',
    iosBundleId: 'com.example.studentsFollowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIL70AJtlxSAu5CWLfJcX0hjMtjuhDlMs',
    appId: '1:700953421587:web:f67bca848f2b6c22db9ce6',
    messagingSenderId: '700953421587',
    projectId: 'students-7ae0a',
    authDomain: 'students-7ae0a.firebaseapp.com',
    storageBucket: 'students-7ae0a.appspot.com',
    measurementId: 'G-97KJ5RKGPX',
  );
}
